### ISSUE TITLE
FDATools Installation

### ISSUE THREAD

**Issue by KhushSingh** [HITS-MBM/gromacs-fda#13]
Hi Bernd,

I am trying to install FDATools to directly import and analyze my average pair-wise force data (.fm file) using atomGraph and resGraph within the package. On typing <install.packages('FDAtools')> on R console, I am receiving the following error :
 **Warning in install.packages 
package ‘FDAtools’ is not available (for R version 3.3.3)**

Which version of R has FDAtools package? Looking forward to hearing from you.

Thanks,
Khushboo

**Comment by BerndDoser** [comment]
Hi Khushboo,

the FDAtools are obsolete and were replace by the GROMACS analysis tools, descriped in the [FDA manual](https://github.com/HITS-MBM/gromacs-fda/blob/master-fda/fda-manual/fda-manual.pdf) chapter 5. The packages in [fda-archive](https://github.com/HITS-MBM/fda-archive) are only provided for backward compatibility reasons and will not be supported anymore. Therefore, I highly recommend to use the new FDA version and analysis tools. However, if you still interested in using the old FDAtools you have to install it as described at [fda-archive/README.md](https://github.com/HITS-MBM/fda-archive/blob/master/README.md) typing `R CMD INSTALL FDAtools_1.0.tar.gz` outside the R console.

Best regards,
Bernd

**Comment by BerndDoser** [comment]
Hi Khushboo,

I stlll strongly recommend an upgrade to the newest FDA version and analysis tools. Its better to spend your time into the installation of the new version than to learn the usage of the old tools. I am also not very helpful since I worked only with the new TRFDA version. The only hint I can give is that the filename 'scalar_avg.fm' is not an object. You should first read the file into a data object using 'data(scalar_avg)' and use than the data object with 'as.matrix(scalar_fm)', as described in the example atomGraph documentation you found at R docs.

Best regards,
Bernd

**Comment by BerndDoser** [comment]
Please reopen the issue or create a new one in case of more questions.
