### ISSUE TITLE
Installation issue - qsort

### ISSUE THREAD

**Issue by mohammadsp** [HITS-MBM/gromacs-fda#32]
_cmake_ works fine, but _make_ fails with the following error:

`/Users/mohammad/Downloads/gromacs-fda-2019.3-fda2.9.1/src/gromacs/mdlib/shake.cpp:228:10: error: no member named 'qsort' in namespace 'std'
    std::qsort(sb, ncons, sizeof(*sb), pcomp);`
`1 error generated.`
`make[2]: *** [src/gromacs/CMakeFiles/libgromacs.dir/mdlib/shake.cpp.o] Error 1`
`make[1]: *** [src/gromacs/CMakeFiles/libgromacs.dir/all] Error 2`
`make: *** [all] Error 2`

Commenting out the qsort line results in a successful compile but gives error at linking stage.

FDA version: 2019.3
OS: macOS High Sierra 10.13.6
Compiler: clang

**Comment by mohammadsp** [comment]
Adding `#include <stdlib.h>` and changing `std::qsort` to `qsort` in `src/gromacs/mdlib/shake.cpp` fixed the issue.

**Comment by BerndDoser** [comment]
Thanks for your report. I always prefer the C++ version. I will try to find out why std::qsort is not found.

**Comment by BerndDoser** [comment]
The reported behavior is not only for FDA, but also for the unchanged GROMACS code. I was able to reproduce the issue on travis using osx xcode 8.3 (see https://travis-ci.org/HITS-MBM/gromacs-fda/jobs/649930599). The issue was fixed by using osx xcode 11.3 (see https://travis-ci.org/HITS-MBM/gromacs-fda/jobs/649930600).

Therefore, I would recommend to update your clang compiler.
